# Conda env file to build and update environment as needed.
# To activate and update this environment from a conda terminal:
# conda activate hundred_day_challenge_env
# conda env update --file environment.yml
name: hundred_day_challenge_env
dependencies:
  - python=3.12
  - pip # install pip in env
  - pip: # Include pip dependencies last
    - prettytable
    - requests
    - colorgram.py
    - pandas
    - twilio